import type { Locale } from "./i18n";

export const UI_STRINGS: Record<Locale, Record<string, string>> = {
  en: {
    // Header
    "app.title": "Franciscan Prayer",
    "app.subtitle": "The Hours · The Rule · The Gospel",
    "app.sound_on": "Sound On",
    "app.sound_off": "Sound Off",
    "audio.listen": "Listen",
    "audio.stop": "Stop",
    "audio.loading": "Loading Audio",

    // Progress
    "progress.title": "Today's Progress",
    "progress.paters": "Paters",
    "progress.hours_of": "of",
    "progress.hours_label": "Hours",
    "progress.complete": "Complete! Deo Gratias!",

    // Home
    "home.pray_now": "Pray Now",
    "home.paters": "Paters",
    "home.feast_today": "Today's Franciscan Feast",
    "home.back": "Home",

    // Nav tiles
    "nav.hours": "Pray the Hours",
    "nav.hours_sub": "Original Pater Count · 83 per day",
    "nav.crown": "Franciscan Crown Rosary",
    "nav.crown_sub": "7 Joys of Mary · 72 Hail Marys",
    "nav.office": "Full Liturgy of the Hours",
    "nav.office_sub": "Complete texts on DivineOffice.org",
    "nav.stations": "Stations of the Cross",
    "nav.stations_sub": "14 Stations · A Franciscan devotion",
    "nav.prayers": "Prayers",
    "nav.prayers_sub": "13 prayers in 5 languages · Franciscan & traditional",
    "nav.rule": "The Rule of St. Francis",
    "nav.rule_sub": "Daily reading from the Regula Bullata (1223)",
    "nav.calendar": "Franciscan Calendar",
    "nav.calendar_sub": "feasts · Saints, solemnities, memorials",
    "nav.readings": "Daily Mass Readings",
    "nav.readings_sub": "Today's readings on USCCB",
    "nav.community": "Franciscan Family",
    "nav.community_sub": "Orders, communities · Find your vocation",
    "nav.intentions": "Prayer Intentions",
    "nav.intentions_sub": "Your private prayer journal",
    "nav.dashboard": "Prayer Dashboard",
    "nav.dashboard_sub": "Stats, streaks · Multi-device sync",
    "nav.settings": "Settings",
    "nav.settings_sub": "Language, theme · App preferences",
    "nav.about": "About & How to Pray",
    "nav.about_sub": "The Franciscan prayer tradition",

    // Hours
    "hours.title": "The Hours — Original Pater Rule",
    "hours.desc": "The original Franciscan practice: 76 Our Fathers per day, distributed across the eight canonical hours. From Chapter III of the Rule.",
    "hours.during_night": "During the night or early morning",
    "hours.dawn": "Dawn / Early morning",

    // Prayer counter
    "counter.tap": "Tap to count each Pater Noster",
    "counter.pacing": "Meditative pacing — bell sounds each interval",
    "counter.completed": "Completed — Deo Gratias!",
    "counter.reset": "Reset",
    "counter.timer": "Pacing Timer",
    "counter.stop_timer": "Stop Timer",
    "counter.pause": "Pause",
    "counter.resume": "Resume",
    "counter.of": "of",
    "counter.gloria_reminder": "Gloria Patri after each Pater Noster",
    "counter.requiem_reminder": "Requiem aeternam after each Pater Noster",

    // Crown
    "crown.title": "Franciscan Crown Rosary",
    "crown.begin": "Begin the Crown",
    "crown.complete": "Crown Complete!",
    "crown.decades": "7 decades",
    "crown.hail_marys": "72 Hail Marys",
    "crown.closing_instruction": "Now pray 1 Our Father, 1 Hail Mary, and 1 Glory Be for the Holy Father.",
    "crown.start_over": "Start Over",
    "crown.joy": "Joy",
    "crown.decade": "Decade",
    "crown.fruit": "Fruit",
    "crown.tap_our_father": "Tap for\nOur Father",
    "crown.of_hail_marys": "of 10 Hail Marys",
    "crown.of": "of",

    // Office
    "office.title": "Liturgy of the Hours",

    // Stations
    "stations.title": "Stations of the Cross",
    "stations.intro": "The Stations of the Cross is a Franciscan devotion. The Franciscans, as custodians of the Holy Land, popularized this meditation on Christ's Passion. Walk with Jesus from His condemnation to His burial through 14 stations of prayer.",
    "stations.begin": "Begin the Way of the Cross",
    "stations.complete": "Way of the Cross Complete",
    "stations.station": "Station",
    "stations.of": "of",
    "stations.scripture": "Scripture",
    "stations.meditation": "Meditation",
    "stations.previous": "Previous",
    "stations.next": "Next",
    "stations.finish": "Finish",
    "stations.start_over": "Start Over",
    "stations.pray_instruction": "Pray 1 Our Father, 1 Hail Mary, 1 Glory Be",

    // Prayers
    "prayers.title": "Prayers",

    // Rule
    "rule.title": "The Rule of St. Francis",

    // Calendar
    "calendar.title": "Franciscan Calendar",
    "calendar.desc": "Feasts, memorials, and solemnities proper to the Franciscan family.",

    // Community
    "community.title": "The Franciscan Family",
    "community.desc": "The Franciscan movement spans 800+ years and includes friars, sisters, contemplatives, and lay people across the world.",
    "community.all": "All Families",
    "community.visit_website": "Visit Website",
    "community.filter_male": "First Order & Male Religious",
    "community.filter_female": "Second Order & Female Religious",
    "community.filter_secular": "Third Order & Secular",

    // Liturgical Banner
    "banner.holy_day": "Holy Day of Obligation",
    "banner.psalm": "Ps ",
    "banner.read_usccb": "Read today\u2019s readings on USCCB",

    // Saints of the Day
    "saints.title": "Saints of the Day",
    "saints.subtitle_public": "View today's saints on Saint for a Minute",
    "saints.subtitle_logged_in": "Today's saints and their stories",
    "saints.view_today": "View Today's Saints",

    // Intentions
    "intentions.title": "Prayer Intentions",
    "intentions.desc": "Offer your prayers for these intentions. Your intentions are private and stored only on your device.",
    "intentions.add": "Add an Intention",
    "intentions.add_btn": "Add Intention",
    "intentions.cancel": "Cancel",
    "intentions.placeholder": "For whom or what would you like to pray?",
    "intentions.empty": "No intentions yet",
    "intentions.empty_sub": "Add your prayer intentions above",

    // Dashboard
    "dashboard.title": "Prayer Dashboard",
    "dashboard.cloud_active": "Cloud Sync Active",
    "dashboard.local_only": "Local Only",
    "dashboard.sync_now": "Sync Now",
    "dashboard.syncing": "Syncing...",
    "dashboard.signed_in": "Signed in as",
    "dashboard.sign_in_prompt": "Sign in to sync your prayer data across devices",
    "dashboard.streak": "Current Streak",
    "dashboard.active_days": "Active Days (30d)",
    "dashboard.hours_prayed": "Hours Prayed (30d)",
    "dashboard.total_paters": "Total Paters (30d)",
    "dashboard.perfect_days": "perfect days in the last 30 days",
    "dashboard.perfect_note": "All 76 Paters completed — Deo Gratias!",
    "dashboard.last_30": "Last 30 Days",
    "dashboard.less": "Less",
    "dashboard.more": "More",
    "dashboard.days": "days",
    "dashboard.of_30": "of 30",

    // About
    "about.title": "About & How to Pray",

    // Settings
    "settings.title": "Settings",
    "settings.account": "Account & Sync",
    "settings.account_desc": "Sign in to sync your prayer progress across devices.",
    "settings.notifications": "Prayer Reminders",
    "settings.notifications_desc": "Turn reminders on or off for the Hours and daily prayer rhythm.",
    "settings.notifications_on": "Reminders On",
    "settings.notifications_off": "Enable Reminders",
    "settings.language": "Language",
    "settings.language_desc": "Choose your preferred app language.",
    "settings.appearance": "Appearance",
    "settings.theme_light": "Light",
    "settings.theme_dark": "Dark",

    // Examination
    "exam.title": "Examination of Conscience",
    "exam.intro": "In the tradition of St. Francis, take a few moments to review your day with honesty and gentleness. God is merciful — this is not about guilt but about growing closer to Him.",
    "exam.begin": "Begin Examination",
    "exam.skip": "Skip for now",
    "exam.complete_title": "Examination Complete",
    "exam.complete_text": "Thank God for His mercy. Entrust your failings to His grace and rest in His peace. Tomorrow is a new day to begin again.",
    "exam.complete_prayer": "Lord, into Your hands I commend my spirit. Watch over me as I sleep, and raise me up to serve You with renewed love tomorrow.",
    "exam.amen": "Amen — Continue to Compline",
    "exam.yes": "Yes, I did well",
    "exam.grow": "I can grow here",
    "exam.back": "Back",
    "exam.next": "Next",
    "exam.finish": "Finish",

    // Auth
    "auth.sign_in": "Sign In",
    "auth.sign_up": "Sign Up",
    "auth.sign_out": "Sign Out",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.google": "Continue with Google",

    // Footer
    "footer.pax": "Pax et Bonum",
    "footer.amdg": "Ad Maiorem Dei Gloriam",

    // Onboarding
    "onboarding.lang_title": "Choose Your Language",
    "onboarding.continue": "Continue",
    "onboarding.skip": "Skip",
    "onboarding.next": "Next",
    "onboarding.start": "Start Praying",
    "onboarding.step1_title": "Welcome to Franciscan Prayer",
    "onboarding.step1_body": "Pray as a Franciscan every day. Whether you are a friar, a sister, a secular Franciscan, or anyone drawn to the spirituality of St. Francis, this app helps you live the Franciscan prayer tradition.",
    "onboarding.step2_title": "The Original Pater Count",
    "onboarding.step2_body": "The Rule of St. Francis (1223) prescribes 76 Our Fathers per day across 8 canonical hours. Tap to count each prayer as you pray. The app tracks your daily progress and helps you build a consistent prayer habit.",
    "onboarding.step3_title": "Rich Franciscan Tradition",
    "onboarding.step3_body": "Explore the Franciscan Crown Rosary, Stations of the Cross, 13 prayers in 5 languages, daily readings from the Rule, quotes from Franciscan saints, and an examination of conscience for Compline. Everything you need to pray as a Franciscan.",

    // Misc
    "share.title": "All 76 Paters Complete!",
    "share.streak": "day streak",
    "share.footer": "Pax et Bonum — franciscan-prayer.pages.dev",
  },

  es: {
    "app.title": "Oración Franciscana",
    "app.subtitle": "Las Horas · La Regla · El Evangelio",
    "app.sound_on": "Sonido",
    "app.sound_off": "Sin Sonido",
    "audio.listen": "Escuchar",
    "audio.stop": "Detener",
    "audio.loading": "Cargando audio",

    "progress.title": "Progreso de Hoy",
    "progress.paters": "Padrenuestros",
    "progress.hours_of": "de",
    "progress.hours_label": "Horas",
    "progress.complete": "¡Completado! ¡Deo Gratias!",

    "home.pray_now": "Rezar Ahora",
    "home.paters": "Padrenuestros",
    "home.feast_today": "Fiesta Franciscana de Hoy",
    "home.back": "Inicio",

    "nav.hours": "Rezar las Horas",
    "nav.hours_sub": "Recuento Original de Padrenuestros · 83 por día",
    "nav.crown": "Corona Franciscana",
    "nav.crown_sub": "7 Gozos de María · 72 Avemarías",
    "nav.office": "Liturgia de las Horas Completa",
    "nav.office_sub": "Textos completos en DivineOffice.org",
    "nav.stations": "Viacrucis",
    "nav.stations_sub": "14 Estaciones · Devoción franciscana",
    "nav.prayers": "Oraciones",
    "nav.prayers_sub": "13 oraciones en 5 idiomas · Franciscanas y tradicionales",
    "nav.rule": "La Regla de San Francisco",
    "nav.rule_sub": "Lectura diaria de la Regula Bullata (1223)",
    "nav.calendar": "Calendario Franciscano",
    "nav.calendar_sub": "fiestas · Santos, solemnidades, memoriales",
    "nav.readings": "Lecturas de la Misa",
    "nav.readings_sub": "Lecturas de hoy en USCCB",
    "nav.community": "Familia Franciscana",
    "nav.community_sub": "Órdenes, comunidades · Encuentra tu vocación",
    "nav.intentions": "Intenciones de Oración",
    "nav.intentions_sub": "Tu diario privado de oración",
    "nav.dashboard": "Panel de Oración",
    "nav.dashboard_sub": "Estadísticas, rachas · Sincronización multidispositivo",
    "nav.settings": "Configuración",
    "nav.settings_sub": "Idioma, tema · Preferencias",
    "nav.about": "Acerca de y Cómo Rezar",
    "nav.about_sub": "La tradición de oración franciscana",

    "hours.title": "Las Horas — Regla Original del Pater",
    "hours.desc": "La práctica franciscana original: 76 Padrenuestros por día, distribuidos en las ocho horas canónicas. Del Capítulo III de la Regla.",

    "counter.tap": "Toca para contar cada Padrenuestro",
    "counter.pacing": "Ritmo meditativo — campana suena en cada intervalo",
    "counter.completed": "¡Completado — Deo Gratias!",
    "counter.reset": "Reiniciar",
    "counter.timer": "Temporizador",
    "counter.stop_timer": "Detener",
    "counter.pause": "Pausa",
    "counter.resume": "Continuar",
    "counter.of": "de",
    "counter.gloria_reminder": "Gloria Patri después de cada Padrenuestro",
    "counter.requiem_reminder": "Requiem aeternam después de cada Padrenuestro",

    "crown.title": "Corona Franciscana",
    "crown.begin": "Comenzar la Corona",
    "crown.complete": "¡Corona Completada!",
    "crown.decades": "7 decenas",
    "crown.hail_marys": "72 Avemarías",
    "crown.closing_instruction": "Ahora reza 1 Padrenuestro, 1 Avemaría y 1 Gloria al Padre por el Santo Padre.",
    "crown.start_over": "Comenzar de nuevo",
    "crown.joy": "Gozo",
    "crown.decade": "Decena",
    "crown.fruit": "Fruto",
    "crown.tap_our_father": "Toca para\nPadrenuestro",
    "crown.of_hail_marys": "de 10 Avemarías",
    "crown.of": "de",
    "office.title": "Liturgia de las Horas",
    "stations.title": "Viacrucis",
    "stations.intro": "El Viacrucis es una devoción franciscana. Los franciscanos, como custodios de Tierra Santa, popularizaron esta meditación sobre la Pasión de Cristo. Camina con Jesús desde su condena hasta su sepultura a través de 14 estaciones de oración.",
    "stations.begin": "Comenzar el Viacrucis",
    "stations.complete": "Viacrucis Completado",
    "stations.station": "Estación",
    "stations.of": "de",
    "stations.scripture": "Escritura",
    "stations.meditation": "Meditación",
    "stations.previous": "Anterior",
    "stations.next": "Siguiente",
    "stations.finish": "Terminar",
    "stations.start_over": "Comenzar de nuevo",
    "stations.pray_instruction": "Reza 1 Padrenuestro, 1 Avemaría, 1 Gloria",
    "prayers.title": "Oraciones",
    "rule.title": "La Regla de San Francisco",
    "calendar.title": "Calendario Franciscano",
    "calendar.desc": "Fiestas, memoriales y solemnidades propias de la familia franciscana.",
    "community.title": "La Familia Franciscana",
    "community.desc": "El movimiento franciscano abarca más de 800 años e incluye frailes, hermanas, contemplativos y laicos en todo el mundo.",
    "community.all": "Todas las Familias",
    "community.visit_website": "Visitar Sitio Web",
    "community.filter_male": "Primera Orden y Religiosos",
    "community.filter_female": "Segunda Orden y Religiosas",
    "community.filter_secular": "Tercera Orden y Seglares",

    "banner.holy_day": "Día de Precepto",
    "banner.psalm": "Sal ",
    "banner.read_usccb": "Leer las lecturas de hoy en USCCB",

    "saints.title": "Santos del Día",
    "saints.subtitle_public": "Ver los santos de hoy en Saint for a Minute",
    "saints.subtitle_logged_in": "Santos de hoy y sus historias",
    "saints.view_today": "Ver Santos de Hoy",

    "intentions.title": "Intenciones de Oración",
    "intentions.desc": "Ofrece tus oraciones por estas intenciones. Tus intenciones son privadas y se almacenan solo en tu dispositivo.",
    "intentions.add": "Añadir una Intención",
    "intentions.add_btn": "Añadir Intención",
    "intentions.cancel": "Cancelar",
    "intentions.placeholder": "¿Por quién o por qué deseas rezar?",
    "intentions.empty": "Sin intenciones aún",
    "intentions.empty_sub": "Añade tus intenciones de oración arriba",

    "dashboard.title": "Panel de Oración",
    "dashboard.cloud_active": "Sincronización Activa",
    "dashboard.local_only": "Solo Local",
    "dashboard.sync_now": "Sincronizar",
    "dashboard.syncing": "Sincronizando...",
    "dashboard.signed_in": "Sesión como",
    "dashboard.sign_in_prompt": "Inicia sesión para sincronizar tus datos de oración entre dispositivos",
    "dashboard.streak": "Racha Actual",
    "dashboard.active_days": "Días Activos (30d)",
    "dashboard.hours_prayed": "Horas Rezadas (30d)",
    "dashboard.total_paters": "Total Padrenuestros (30d)",
    "dashboard.perfect_days": "días perfectos en los últimos 30 días",
    "dashboard.perfect_note": "¡76 Padrenuestros completados — Deo Gratias!",
    "dashboard.last_30": "Últimos 30 Días",
    "dashboard.less": "Menos",
    "dashboard.more": "Más",
    "dashboard.days": "días",
    "dashboard.of_30": "de 30",

    "about.title": "Acerca de y Cómo Rezar",

    "settings.title": "Configuración",
    "settings.account": "Cuenta y sincronización",
    "settings.account_desc": "Inicia sesión para sincronizar tu progreso de oración entre dispositivos.",
    "settings.notifications": "Recordatorios de oración",
    "settings.notifications_desc": "Activa o desactiva los recordatorios para las Horas y la oración diaria.",
    "settings.notifications_on": "Recordatorios activos",
    "settings.notifications_off": "Activar recordatorios",
    "settings.language": "Idioma",
    "settings.language_desc": "Elige tu idioma preferido para la app.",
    "settings.appearance": "Apariencia",
    "settings.theme_light": "Claro",
    "settings.theme_dark": "Oscuro",

    "exam.title": "Examen de Conciencia",
    "exam.intro": "En la tradición de San Francisco, toma unos momentos para revisar tu día con honestidad y gentileza. Dios es misericordioso — no se trata de culpa sino de acercarse más a Él.",
    "exam.begin": "Comenzar Examen",
    "exam.skip": "Omitir por ahora",
    "exam.complete_title": "Examen Completo",
    "exam.complete_text": "Da gracias a Dios por su misericordia. Confía tus faltas a su gracia y descansa en su paz. Mañana es un nuevo día para comenzar de nuevo.",
    "exam.complete_prayer": "Señor, en tus manos encomiendo mi espíritu. Vela sobre mí mientras duermo y levántame para servirte con amor renovado mañana.",
    "exam.amen": "Amén — Continuar a Completas",
    "exam.yes": "Sí, lo hice bien",
    "exam.grow": "Puedo crecer aquí",
    "exam.back": "Atrás",
    "exam.next": "Siguiente",
    "exam.finish": "Terminar",

    "auth.sign_in": "Iniciar Sesión",
    "auth.sign_up": "Registrarse",
    "auth.sign_out": "Cerrar Sesión",
    "auth.email": "Correo",
    "auth.password": "Contraseña",
    "auth.google": "Continuar con Google",

    "footer.pax": "Pax et Bonum",
    "footer.amdg": "Ad Maiorem Dei Gloriam",

    "onboarding.lang_title": "Elige tu idioma",
    "onboarding.continue": "Continuar",
    "onboarding.skip": "Omitir",
    "onboarding.next": "Siguiente",
    "onboarding.start": "Comenzar a Rezar",
    "onboarding.step1_title": "Bienvenido a Oración Franciscana",
    "onboarding.step1_body": "Reza como franciscano cada día. Ya seas fraile, hermana, franciscano seglar, o cualquiera atraído por la espiritualidad de San Francisco, esta app te ayuda a vivir la tradición de oración franciscana.",
    "onboarding.step2_title": "El Recuento Original del Padrenuestro",
    "onboarding.step2_body": "La Regla de San Francisco (1223) prescribe 76 Padrenuestros por día en 8 horas canónicas. Toca para contar cada oración mientras rezas. La app rastrea tu progreso diario y te ayuda a construir un hábito de oración constante.",
    "onboarding.step3_title": "Rica Tradición Franciscana",
    "onboarding.step3_body": "Explora la Corona Franciscana, el Viacrucis, 13 oraciones en 5 idiomas, lecturas diarias de la Regla, citas de santos franciscanos, y un examen de conciencia para Completas. Todo lo que necesitas para rezar como franciscano.",

    "share.title": "¡76 Padrenuestros Completados!",
    "share.streak": "días de racha",
    "share.footer": "Pax et Bonum — franciscan-prayer.pages.dev",
  },

  it: {
    "app.title": "Preghiera Francescana",
    "app.subtitle": "Le Ore · La Regola · Il Vangelo",
    "app.sound_on": "Suono",
    "app.sound_off": "Muto",
    "audio.listen": "Ascolta",
    "audio.stop": "Ferma",
    "audio.loading": "Caricamento audio",

    "progress.title": "Progresso di Oggi",
    "progress.paters": "Pater",
    "progress.hours_of": "di",
    "progress.hours_label": "Ore",
    "progress.complete": "Completato! Deo Gratias!",

    "home.pray_now": "Prega Ora",
    "home.paters": "Pater",
    "home.feast_today": "Festa Francescana di Oggi",
    "home.back": "Home",

    "nav.hours": "Prega le Ore",
    "nav.hours_sub": "Conteggio Originale dei Pater · 83 al giorno",
    "nav.crown": "Corona Francescana",
    "nav.crown_sub": "7 Gioie di Maria · 72 Ave Maria",
    "nav.office": "Liturgia delle Ore Completa",
    "nav.office_sub": "Testi completi su DivineOffice.org",
    "nav.stations": "Via Crucis",
    "nav.stations_sub": "14 Stazioni · Devozione francescana",
    "nav.prayers": "Preghiere",
    "nav.prayers_sub": "13 preghiere in 5 lingue · Francescane e tradizionali",
    "nav.rule": "La Regola di San Francesco",
    "nav.rule_sub": "Lettura quotidiana dalla Regula Bullata (1223)",
    "nav.calendar": "Calendario Francescano",
    "nav.calendar_sub": "feste · Santi, solennità, memorie",
    "nav.readings": "Letture della Messa",
    "nav.readings_sub": "Letture di oggi su USCCB",
    "nav.community": "Famiglia Francescana",
    "nav.community_sub": "Ordini, comunità · Trova la tua vocazione",
    "nav.intentions": "Intenzioni di Preghiera",
    "nav.intentions_sub": "Il tuo diario privato di preghiera",
    "nav.dashboard": "Cruscotto di Preghiera",
    "nav.dashboard_sub": "Statistiche, serie · Sincronizzazione multi-dispositivo",
    "nav.settings": "Impostazioni",
    "nav.settings_sub": "Lingua, tema · Preferenze app",
    "nav.about": "Informazioni e Come Pregare",
    "nav.about_sub": "La tradizione di preghiera francescana",

    "hours.title": "Le Ore — Regola Originale del Pater",
    "hours.desc": "La pratica francescana originale: 76 Pater Noster al giorno, distribuiti nelle otto ore canoniche. Dal Capitolo III della Regola.",

    "counter.tap": "Tocca per contare ogni Pater Noster",
    "counter.pacing": "Ritmo meditativo — campana ad ogni intervallo",
    "counter.completed": "Completato — Deo Gratias!",
    "counter.reset": "Ricomincia",
    "counter.timer": "Timer",
    "counter.stop_timer": "Ferma",
    "counter.pause": "Pausa",
    "counter.resume": "Riprendi",
    "counter.of": "di",
    "counter.gloria_reminder": "Gloria Patri dopo ogni Pater Noster",
    "counter.requiem_reminder": "Requiem aeternam dopo ogni Pater Noster",

    "crown.title": "Corona Francescana",
    "crown.begin": "Inizia la Corona",
    "crown.complete": "Corona Completata!",
    "crown.decades": "7 decine",
    "crown.hail_marys": "72 Ave Maria",
    "crown.closing_instruction": "Ora prega 1 Padre Nostro, 1 Ave Maria e 1 Gloria al Padre per il Santo Padre.",
    "crown.start_over": "Ricomincia",
    "crown.joy": "Gioia",
    "crown.decade": "Decina",
    "crown.fruit": "Frutto",
    "crown.tap_our_father": "Tocca per\nPadre Nostro",
    "crown.of_hail_marys": "di 10 Ave Maria",
    "crown.of": "di",
    "office.title": "Liturgia delle Ore",
    "stations.title": "Via Crucis",
    "stations.intro": "La Via Crucis è una devozione francescana. I francescani, come custodi della Terra Santa, hanno diffuso questa meditazione sulla Passione di Cristo. Cammina con Gesù dalla sua condanna alla sua sepoltura attraverso 14 stazioni di preghiera.",
    "stations.begin": "Inizia la Via Crucis",
    "stations.complete": "Via Crucis Completata",
    "stations.station": "Stazione",
    "stations.of": "di",
    "stations.scripture": "Scrittura",
    "stations.meditation": "Meditazione",
    "stations.previous": "Precedente",
    "stations.next": "Avanti",
    "stations.finish": "Fine",
    "stations.start_over": "Ricomincia",
    "stations.pray_instruction": "Prega 1 Padre Nostro, 1 Ave Maria, 1 Gloria",
    "prayers.title": "Preghiere",
    "rule.title": "La Regola di San Francesco",
    "calendar.title": "Calendario Francescano",
    "calendar.desc": "Feste, memorie e solennità proprie della famiglia francescana.",
    "community.title": "La Famiglia Francescana",
    "community.desc": "Il movimento francescano abbraccia più di 800 anni e comprende frati, suore, contemplativi e laici in tutto il mondo.",
    "community.all": "Tutte le Famiglie",
    "community.visit_website": "Visita il Sito",
    "community.filter_male": "Primo Ordine e Religiosi",
    "community.filter_female": "Secondo Ordine e Religiose",
    "community.filter_secular": "Terz'Ordine e Secolari",

    "banner.holy_day": "Giorno di Precetto",
    "banner.psalm": "Sal ",
    "banner.read_usccb": "Leggi le letture di oggi su USCCB",

    "saints.title": "Santi del Giorno",
    "saints.subtitle_public": "Vedi i santi di oggi su Saint for a Minute",
    "saints.subtitle_logged_in": "Santi di oggi e le loro storie",
    "saints.view_today": "Vedi Santi di Oggi",

    "intentions.title": "Intenzioni di Preghiera",
    "intentions.desc": "Offri le tue preghiere per queste intenzioni. Le tue intenzioni sono private e conservate solo sul tuo dispositivo.",
    "intentions.add": "Aggiungi un'Intenzione",
    "intentions.add_btn": "Aggiungi Intenzione",
    "intentions.cancel": "Annulla",
    "intentions.placeholder": "Per chi o per cosa desideri pregare?",
    "intentions.empty": "Nessuna intenzione",
    "intentions.empty_sub": "Aggiungi le tue intenzioni di preghiera sopra",

    "dashboard.title": "Cruscotto di Preghiera",
    "dashboard.cloud_active": "Sincronizzazione Attiva",
    "dashboard.local_only": "Solo Locale",
    "dashboard.sync_now": "Sincronizza",
    "dashboard.syncing": "Sincronizzazione...",
    "dashboard.signed_in": "Accesso come",
    "dashboard.sign_in_prompt": "Accedi per sincronizzare i tuoi dati di preghiera tra dispositivi",
    "dashboard.streak": "Serie Attuale",
    "dashboard.active_days": "Giorni Attivi (30g)",
    "dashboard.hours_prayed": "Ore Pregate (30g)",
    "dashboard.total_paters": "Totale Pater (30g)",
    "dashboard.perfect_days": "giorni perfetti negli ultimi 30 giorni",
    "dashboard.perfect_note": "76 Pater completati — Deo Gratias!",
    "dashboard.last_30": "Ultimi 30 Giorni",
    "dashboard.less": "Meno",
    "dashboard.more": "Più",
    "dashboard.days": "giorni",
    "dashboard.of_30": "di 30",

    "about.title": "Informazioni e Come Pregare",

    "settings.title": "Impostazioni",
    "settings.account": "Account e sincronizzazione",
    "settings.account_desc": "Accedi per sincronizzare i tuoi progressi di preghiera tra dispositivi.",
    "settings.notifications": "Promemoria di preghiera",
    "settings.notifications_desc": "Attiva o disattiva i promemoria per le Ore e la preghiera quotidiana.",
    "settings.notifications_on": "Promemoria attivi",
    "settings.notifications_off": "Attiva promemoria",
    "settings.language": "Lingua",
    "settings.language_desc": "Scegli la lingua preferita dell'app.",
    "settings.appearance": "Aspetto",
    "settings.theme_light": "Chiaro",
    "settings.theme_dark": "Scuro",

    "exam.title": "Esame di Coscienza",
    "exam.intro": "Nella tradizione di San Francesco, prenditi qualche momento per rivedere la tua giornata con onestà e dolcezza. Dio è misericordioso — non si tratta di senso di colpa ma di avvicinarsi a Lui.",
    "exam.begin": "Inizia l'Esame",
    "exam.skip": "Salta per ora",
    "exam.complete_title": "Esame Completo",
    "exam.complete_text": "Ringrazia Dio per la sua misericordia. Affida i tuoi difetti alla sua grazia e riposa nella sua pace. Domani è un nuovo giorno per ricominciare.",
    "exam.complete_prayer": "Signore, nelle tue mani affido il mio spirito. Veglia su di me mentre dormo e svegliami per servirti con amore rinnovato domani.",
    "exam.amen": "Amen — Continua a Compieta",
    "exam.yes": "Sì, ho fatto bene",
    "exam.grow": "Posso crescere qui",
    "exam.back": "Indietro",
    "exam.next": "Avanti",
    "exam.finish": "Fine",

    "auth.sign_in": "Accedi",
    "auth.sign_up": "Registrati",
    "auth.sign_out": "Esci",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.google": "Continua con Google",

    "footer.pax": "Pax et Bonum",
    "footer.amdg": "Ad Maiorem Dei Gloriam",

    "onboarding.lang_title": "Scegli la tua lingua",
    "onboarding.continue": "Continua",
    "onboarding.skip": "Salta",
    "onboarding.next": "Avanti",
    "onboarding.start": "Inizia a Pregare",
    "onboarding.step1_title": "Benvenuto in Preghiera Francescana",
    "onboarding.step1_body": "Prega come un francescano ogni giorno. Che tu sia un frate, una suora, un francescano secolare, o chiunque attratto dalla spiritualità di San Francesco, questa app ti aiuta a vivere la tradizione di preghiera francescana.",
    "onboarding.step2_title": "Il Conteggio Originale del Pater",
    "onboarding.step2_body": "La Regola di San Francesco (1223) prescrive 76 Pater Noster al giorno nelle 8 ore canoniche. Tocca per contare ogni preghiera mentre preghi. L'app tiene traccia del tuo progresso quotidiano e ti aiuta a costruire un'abitudine di preghiera costante.",
    "onboarding.step3_title": "Ricca Tradizione Francescana",
    "onboarding.step3_body": "Esplora la Corona Francescana, la Via Crucis, 13 preghiere in 5 lingue, letture quotidiane della Regola, citazioni di santi francescani, e un esame di coscienza per la Compieta. Tutto ciò che ti serve per pregare come un francescano.",

    "share.title": "76 Pater Completati!",
    "share.streak": "giorni di serie",
    "share.footer": "Pax et Bonum — franciscan-prayer.pages.dev",
  },

  fr: {
    "app.title": "Prière Franciscaine",
    "app.subtitle": "Les Heures · La Règle · L'Évangile",
    "app.sound_on": "Son",
    "app.sound_off": "Muet",
    "audio.listen": "Écouter",
    "audio.stop": "Arrêter",
    "audio.loading": "Chargement audio",

    "progress.title": "Progrès du Jour",
    "progress.paters": "Pater",
    "progress.hours_of": "de",
    "progress.hours_label": "Heures",
    "progress.complete": "Terminé ! Deo Gratias !",

    "home.pray_now": "Prier Maintenant",
    "home.paters": "Pater",
    "home.feast_today": "Fête Franciscaine du Jour",
    "home.back": "Accueil",

    "nav.hours": "Prier les Heures",
    "nav.hours_sub": "Décompte Original des Pater · 83 par jour",
    "nav.crown": "Couronne Franciscaine",
    "nav.crown_sub": "7 Joies de Marie · 72 Je vous salue",
    "nav.office": "Liturgie des Heures Complète",
    "nav.office_sub": "Textes complets sur DivineOffice.org",
    "nav.stations": "Chemin de Croix",
    "nav.stations_sub": "14 Stations · Dévotion franciscaine",
    "nav.prayers": "Prières",
    "nav.prayers_sub": "13 prières en 5 langues · Franciscaines et traditionnelles",
    "nav.rule": "La Règle de Saint François",
    "nav.rule_sub": "Lecture quotidienne de la Regula Bullata (1223)",
    "nav.calendar": "Calendrier Franciscain",
    "nav.calendar_sub": "fêtes · Saints, solennités, mémoires",
    "nav.readings": "Lectures de la Messe",
    "nav.readings_sub": "Lectures du jour sur USCCB",
    "nav.community": "Famille Franciscaine",
    "nav.community_sub": "Ordres, communautés · Trouvez votre vocation",
    "nav.intentions": "Intentions de Prière",
    "nav.intentions_sub": "Votre journal de prière privé",
    "nav.dashboard": "Tableau de Bord",
    "nav.dashboard_sub": "Statistiques, séries · Synchronisation multi-appareils",
    "nav.settings": "Paramètres",
    "nav.settings_sub": "Langue, thème · Préférences app",
    "nav.about": "À propos et Comment Prier",
    "nav.about_sub": "La tradition de prière franciscaine",

    "hours.title": "Les Heures — Règle Originale du Pater",
    "hours.desc": "La pratique franciscaine originale : 76 Notre Père par jour, répartis sur les huit heures canoniques. Du Chapitre III de la Règle.",

    "counter.tap": "Appuyez pour compter chaque Pater Noster",
    "counter.pacing": "Rythme méditatif — cloche à chaque intervalle",
    "counter.completed": "Terminé — Deo Gratias !",
    "counter.reset": "Recommencer",
    "counter.timer": "Minuteur",
    "counter.stop_timer": "Arrêter",
    "counter.pause": "Pause",
    "counter.resume": "Reprendre",
    "counter.of": "de",
    "counter.gloria_reminder": "Gloria Patri après chaque Pater Noster",
    "counter.requiem_reminder": "Requiem aeternam après chaque Pater Noster",

    "crown.title": "Couronne Franciscaine",
    "crown.begin": "Commencer la Couronne",
    "crown.complete": "Couronne Terminée !",
    "crown.decades": "7 dizaines",
    "crown.hail_marys": "72 Je vous salue Marie",
    "crown.closing_instruction": "Priez maintenant 1 Notre Père, 1 Je vous salue Marie et 1 Gloire au Père pour le Saint-Père.",
    "crown.start_over": "Recommencer",
    "crown.joy": "Joie",
    "crown.decade": "Dizaine",
    "crown.fruit": "Fruit",
    "crown.tap_our_father": "Appuyez pour\nNotre Père",
    "crown.of_hail_marys": "de 10 Je vous salue",
    "crown.of": "de",
    "office.title": "Liturgie des Heures",
    "stations.title": "Chemin de Croix",
    "stations.intro": "Le Chemin de Croix est une dévotion franciscaine. Les franciscains, en tant que gardiens de la Terre Sainte, ont popularisé cette méditation sur la Passion du Christ. Marchez avec Jésus de sa condamnation à sa mise au tombeau à travers 14 stations de prière.",
    "stations.begin": "Commencer le Chemin de Croix",
    "stations.complete": "Chemin de Croix Terminé",
    "stations.station": "Station",
    "stations.of": "de",
    "stations.scripture": "Écriture",
    "stations.meditation": "Méditation",
    "stations.previous": "Précédent",
    "stations.next": "Suivant",
    "stations.finish": "Terminer",
    "stations.start_over": "Recommencer",
    "stations.pray_instruction": "Priez 1 Notre Père, 1 Je vous salue Marie, 1 Gloire au Père",
    "prayers.title": "Prières",
    "rule.title": "La Règle de Saint François",
    "calendar.title": "Calendrier Franciscain",
    "calendar.desc": "Fêtes, mémoires et solennités propres à la famille franciscaine.",
    "community.title": "La Famille Franciscaine",
    "community.desc": "Le mouvement franciscain s'étend sur plus de 800 ans et comprend des frères, sœurs, contemplatifs et laïcs à travers le monde.",
    "community.all": "Toutes les Familles",
    "community.visit_website": "Visiter le Site",
    "community.filter_male": "Premier Ordre et Religieux",
    "community.filter_female": "Deuxième Ordre et Religieuses",
    "community.filter_secular": "Tiers-Ordre et Séculiers",

    "banner.holy_day": "Jour d'Obligation",
    "banner.psalm": "Ps ",
    "banner.read_usccb": "Lire les lectures du jour sur USCCB",

    "saints.title": "Saints du Jour",
    "saints.subtitle_public": "Voir les saints d'aujourd'hui sur Saint for a Minute",
    "saints.subtitle_logged_in": "Saints d'aujourd'hui et leurs histoires",
    "saints.view_today": "Voir les Saints d'Aujourd'hui",

    "intentions.title": "Intentions de Prière",
    "intentions.desc": "Offrez vos prières pour ces intentions. Vos intentions sont privées et stockées uniquement sur votre appareil.",
    "intentions.add": "Ajouter une Intention",
    "intentions.add_btn": "Ajouter l'Intention",
    "intentions.cancel": "Annuler",
    "intentions.placeholder": "Pour qui ou pourquoi souhaitez-vous prier ?",
    "intentions.empty": "Pas encore d'intentions",
    "intentions.empty_sub": "Ajoutez vos intentions de prière ci-dessus",

    "dashboard.title": "Tableau de Bord",
    "dashboard.cloud_active": "Synchronisation Active",
    "dashboard.local_only": "Local Uniquement",
    "dashboard.sync_now": "Synchroniser",
    "dashboard.syncing": "Synchronisation...",
    "dashboard.signed_in": "Connecté en tant que",
    "dashboard.sign_in_prompt": "Connectez-vous pour synchroniser vos données de prière entre appareils",
    "dashboard.streak": "Série Actuelle",
    "dashboard.active_days": "Jours Actifs (30j)",
    "dashboard.hours_prayed": "Heures Priées (30j)",
    "dashboard.total_paters": "Total Pater (30j)",
    "dashboard.perfect_days": "jours parfaits dans les 30 derniers jours",
    "dashboard.perfect_note": "76 Pater complétés — Deo Gratias !",
    "dashboard.last_30": "30 Derniers Jours",
    "dashboard.less": "Moins",
    "dashboard.more": "Plus",
    "dashboard.days": "jours",
    "dashboard.of_30": "de 30",

    "about.title": "À propos et Comment Prier",

    "settings.title": "Paramètres",
    "settings.account": "Compte et synchronisation",
    "settings.account_desc": "Connectez-vous pour synchroniser votre progression de prière entre appareils.",
    "settings.notifications": "Rappels de prière",
    "settings.notifications_desc": "Activez ou désactivez les rappels pour les Heures et la prière quotidienne.",
    "settings.notifications_on": "Rappels activés",
    "settings.notifications_off": "Activer les rappels",
    "settings.language": "Langue",
    "settings.language_desc": "Choisissez la langue de l'application.",
    "settings.appearance": "Apparence",
    "settings.theme_light": "Clair",
    "settings.theme_dark": "Sombre",

    "exam.title": "Examen de Conscience",
    "exam.intro": "Dans la tradition de Saint François, prenez quelques instants pour revoir votre journée avec honnêteté et douceur. Dieu est miséricordieux — il ne s'agit pas de culpabilité mais de se rapprocher de Lui.",
    "exam.begin": "Commencer l'Examen",
    "exam.skip": "Passer pour l'instant",
    "exam.complete_title": "Examen Terminé",
    "exam.complete_text": "Remerciez Dieu pour sa miséricorde. Confiez vos manquements à sa grâce et reposez-vous dans sa paix. Demain est un nouveau jour pour recommencer.",
    "exam.complete_prayer": "Seigneur, entre tes mains je remets mon esprit. Veille sur moi pendant mon sommeil et réveille-moi pour te servir avec un amour renouvelé demain.",
    "exam.amen": "Amen — Continuer aux Complies",
    "exam.yes": "Oui, j'ai bien agi",
    "exam.grow": "Je peux grandir ici",
    "exam.back": "Retour",
    "exam.next": "Suivant",
    "exam.finish": "Terminer",

    "auth.sign_in": "Se Connecter",
    "auth.sign_up": "S'inscrire",
    "auth.sign_out": "Se Déconnecter",
    "auth.email": "E-mail",
    "auth.password": "Mot de passe",
    "auth.google": "Continuer avec Google",

    "footer.pax": "Pax et Bonum",
    "footer.amdg": "Ad Maiorem Dei Gloriam",

    "onboarding.lang_title": "Choisissez votre langue",
    "onboarding.continue": "Continuer",
    "onboarding.skip": "Passer",
    "onboarding.next": "Suivant",
    "onboarding.start": "Commencer à Prier",
    "onboarding.step1_title": "Bienvenue dans Prière Franciscaine",
    "onboarding.step1_body": "Priez comme un franciscain chaque jour. Que vous soyez frère, sœur, franciscain séculier, ou toute personne attirée par la spiritualité de Saint François, cette app vous aide à vivre la tradition de prière franciscaine.",
    "onboarding.step2_title": "Le Décompte Original du Pater",
    "onboarding.step2_body": "La Règle de Saint François (1223) prescrit 76 Notre Père par jour sur 8 heures canoniques. Appuyez pour compter chaque prière pendant que vous priez. L'app suit votre progression quotidienne et vous aide à construire une habitude de prière constante.",
    "onboarding.step3_title": "Riche Tradition Franciscaine",
    "onboarding.step3_body": "Explorez la Couronne Franciscaine, le Chemin de Croix, 13 prières en 5 langues, lectures quotidiennes de la Règle, citations de saints franciscains, et un examen de conscience pour les Complies. Tout ce dont vous avez besoin pour prier comme un franciscain.",

    "share.title": "76 Pater Complétés !",
    "share.streak": "jours de série",
    "share.footer": "Pax et Bonum — franciscan-prayer.pages.dev",
  },

  zh: {
    "app.title": "方济各祈祷",
    "app.subtitle": "日课 · 会规 · 福音",
    "app.sound_on": "开启声音",
    "app.sound_off": "静音",
    "audio.listen": "收听",
    "audio.stop": "停止",
    "audio.loading": "音频加载中",

    "progress.title": "今日进度",
    "progress.paters": "天主经",
    "progress.hours_of": "/",
    "progress.hours_label": "时辰",
    "progress.complete": "完成！感谢天主！",

    "home.pray_now": "现在祈祷",
    "home.paters": "天主经",
    "home.feast_today": "今日方济各庆节",
    "home.back": "首页",

    "nav.hours": "日课祈祷",
    "nav.hours_sub": "原始天主经计数 · 每日83遍",
    "nav.crown": "方济各七苦玫瑰经",
    "nav.crown_sub": "圣母七乐 · 72遍圣母经",
    "nav.office": "完整日课经",
    "nav.office_sub": "DivineOffice.org完整经文",
    "nav.stations": "苦路十四处",
    "nav.stations_sub": "14处苦路 · 方济各敬礼",
    "nav.prayers": "祈祷文",
    "nav.prayers_sub": "13篇祈祷 · 5种语言 · 方济各与传统祈祷",
    "nav.rule": "圣方济各会规",
    "nav.rule_sub": "每日诵读《敕准会规》(1223)",
    "nav.calendar": "方济各历",
    "nav.calendar_sub": "庆节 · 圣人、庆日、纪念日",
    "nav.readings": "每日弥撒读经",
    "nav.readings_sub": "今日USCCB读经",
    "nav.community": "方济各大家庭",
    "nav.community_sub": "修会、团体 · 寻找你的圣召",
    "nav.intentions": "祈祷意向",
    "nav.intentions_sub": "你的私人祈祷日志",
    "nav.dashboard": "祈祷仪表盘",
    "nav.dashboard_sub": "统计、连续天数 · 多设备同步",
    "nav.settings": "设置",
    "nav.settings_sub": "语言、主题 · 应用偏好",
    "nav.about": "关于与祈祷指南",
    "nav.about_sub": "方济各祈祷传统",

    "hours.title": "日课 — 原始天主经规则",
    "hours.desc": "方济各原始做法：每日76遍天主经，分布在八个时辰中。出自会规第三章。",

    "counter.tap": "点击计数每遍天主经",
    "counter.pacing": "默想节奏 — 每次间隔响铃",
    "counter.completed": "完成 — 感谢天主！",
    "counter.reset": "重置",
    "counter.timer": "节奏计时",
    "counter.stop_timer": "停止",
    "counter.pause": "暂停",
    "counter.resume": "继续",
    "counter.of": "/",
    "counter.gloria_reminder": "每遍天主经后诵念圣三光荣经",
    "counter.requiem_reminder": "每遍天主经后诵念安息经",

    "crown.title": "方济各七苦玫瑰经",
    "crown.begin": "开始诵念圣冠",
    "crown.complete": "圣冠玫瑰经完成！",
    "crown.decades": "七端",
    "crown.hail_marys": "72遍圣母经",
    "crown.closing_instruction": "现在诵念天主经一遍、圣母经一遍、圣三光荣颂一遍，为教宗的意向祈祷。",
    "crown.start_over": "重新开始",
    "crown.joy": "喜乐",
    "crown.decade": "第",
    "crown.fruit": "神果",
    "crown.tap_our_father": "点击诵念\n天主经",
    "crown.of_hail_marys": "/ 10遍圣母经",
    "crown.of": "/",
    "office.title": "日课经",
    "stations.title": "苦路十四处",
    "stations.intro": "苦路是方济各敬礼。方济各会士作为圣地的守护者，推广了这一默想基督苦难的祈祷方式。与耶稣同行，从被判刑到安葬，经过14处苦路祈祷。",
    "stations.begin": "开始苦路",
    "stations.complete": "苦路完成",
    "stations.station": "第",
    "stations.of": "/",
    "stations.scripture": "圣经",
    "stations.meditation": "默想",
    "stations.previous": "上一处",
    "stations.next": "下一处",
    "stations.finish": "完成",
    "stations.start_over": "重新开始",
    "stations.pray_instruction": "诵念天主经一遍、圣母经一遍、圣三光荣颂一遍",
    "prayers.title": "祈祷文",
    "rule.title": "圣方济各会规",
    "calendar.title": "方济各历",
    "calendar.desc": "方济各大家庭特有的庆节、纪念日和庆日。",
    "community.title": "方济各大家庭",
    "community.desc": "方济各运动跨越800多年，包括世界各地的修士、修女、隐修者和平信徒。",
    "community.all": "所有修会",
    "community.visit_website": "访问网站",
    "community.filter_male": "第一会及男修会",
    "community.filter_female": "第二会及女修会",
    "community.filter_secular": "第三会及在俗修会",

    "banner.holy_day": "当守瞻礼日",
    "banner.psalm": "圣咏 ",
    "banner.read_usccb": "在USCCB阅读今日读经",

    "saints.title": "今日圣人",
    "saints.subtitle_public": "在Saint for a Minute查看今日圣人",
    "saints.subtitle_logged_in": "今日圣人及其故事",
    "saints.view_today": "查看今日圣人",

    "intentions.title": "祈祷意向",
    "intentions.desc": "为这些意向奉献你的祈祷。你的意向是私密的，仅存储在你的设备上。",
    "intentions.add": "添加意向",
    "intentions.add_btn": "添加意向",
    "intentions.cancel": "取消",
    "intentions.placeholder": "你想为谁或为什么祈祷？",
    "intentions.empty": "暂无意向",
    "intentions.empty_sub": "在上方添加你的祈祷意向",

    "dashboard.title": "祈祷仪表盘",
    "dashboard.cloud_active": "云同步已启用",
    "dashboard.local_only": "仅本地",
    "dashboard.sync_now": "立即同步",
    "dashboard.syncing": "同步中...",
    "dashboard.signed_in": "已登录",
    "dashboard.sign_in_prompt": "登录以在多台设备间同步你的祈祷数据",
    "dashboard.streak": "当前连续",
    "dashboard.active_days": "活跃天数(30天)",
    "dashboard.hours_prayed": "已祈祷时辰(30天)",
    "dashboard.total_paters": "天主经总数(30天)",
    "dashboard.perfect_days": "过去30天的完美天数",
    "dashboard.perfect_note": "76遍天主经全部完成 — 感谢天主！",
    "dashboard.last_30": "最近30天",
    "dashboard.less": "少",
    "dashboard.more": "多",
    "dashboard.days": "天",
    "dashboard.of_30": "/ 30",

    "about.title": "关于与祈祷指南",

    "settings.title": "设置",
    "settings.account": "账户与同步",
    "settings.account_desc": "登录后可在不同设备间同步祈祷进度。",
    "settings.notifications": "祈祷提醒",
    "settings.notifications_desc": "开启或关闭时辰祈祷与每日祈祷提醒。",
    "settings.notifications_on": "提醒已开启",
    "settings.notifications_off": "开启提醒",
    "settings.language": "语言",
    "settings.language_desc": "选择应用使用的语言。",
    "settings.appearance": "外观",
    "settings.theme_light": "浅色",
    "settings.theme_dark": "深色",

    "exam.title": "省察",
    "exam.intro": "按照圣方济各的传统，花几分钟以诚实和温柔回顾你的一天。天主是仁慈的——这不是关于内疚，而是关于更接近祂。",
    "exam.begin": "开始省察",
    "exam.skip": "暂时跳过",
    "exam.complete_title": "省察完成",
    "exam.complete_text": "感谢天主的仁慈。将你的过失托付给祂的恩典，在祂的平安中安息。明天是重新开始的新一天。",
    "exam.complete_prayer": "主啊，我将我的灵魂交在你手中。在我睡眠时守护我，唤醒我以更新的爱来事奉你。",
    "exam.amen": "阿门 — 继续晚祷",
    "exam.yes": "是的，我做得好",
    "exam.grow": "我可以成长",
    "exam.back": "返回",
    "exam.next": "下一个",
    "exam.finish": "完成",

    "auth.sign_in": "登录",
    "auth.sign_up": "注册",
    "auth.sign_out": "退出",
    "auth.email": "电子邮件",
    "auth.password": "密码",
    "auth.google": "使用谷歌继续",

    "footer.pax": "和平与美善",
    "footer.amdg": "愈显主荣",

    "onboarding.lang_title": "选择你的语言",
    "onboarding.continue": "继续",
    "onboarding.skip": "跳过",
    "onboarding.next": "下一步",
    "onboarding.start": "开始祈祷",
    "onboarding.step1_title": "欢迎使用方济各祈祷",
    "onboarding.step1_body": "每天像方济各会士一样祈祷。无论你是修士、修女、在俗方济各会员，还是被亚西西圣方济各的灵修吸引的任何人，这个应用帮助你活出方济各祈祷传统。",
    "onboarding.step2_title": "原始天主经计数",
    "onboarding.step2_body": "圣方济各会规（1223年）规定每天在8个时辰中诵念76遍天主经。点击计数每遍祈祷。应用会追踪你的每日进度，帮助你建立持续的祈祷习惯。",
    "onboarding.step3_title": "丰富的方济各传统",
    "onboarding.step3_body": "探索方济各七苦玫瑰经、苦路十四处、5种语言的13篇祈祷、每日会规诵读、方济各圣人名言，以及夜课省察。你需要的一切，都在这里，帮助你像方济各会士一样祈祷。",

    "share.title": "76遍天主经全部完成！",
    "share.streak": "天连续",
    "share.footer": "和平与美善 — franciscan-prayer.pages.dev",
  },
};
